In [1]:
pip install numpy


   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 12.4/12.4 MB 86.4 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
print(a)
print(type(a))


[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [ ]:
a = np.array([[1, 2],
              [3, 4]])
print(a)

b = np.array([[5, 6],
              [7, 8]])
print(a + b) 
# print(a * b) 곱하기는 안씀 
# [1+5  2+6] 
# [3+7  4+8]

[[1 2]
 [3 4]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]


In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])   # 2행3열

b = np.array([[10],
              [20],
              [30]])        # 3행1열

print(a @ b)      #결과는 2행1열  

[[140]
 [320]]


In [ ]:
# 전치행렬
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)